- WCF/NuGet/common/web.config.install.xdt
- WCF/NuGet/common/web.config.uninstall.xdt
… on the default, unnamed service behavior. This can help prevent issues such as https://github.com/Microsoft/ApplicationInsights-SDK-Labs/issues/6 in many basic cases.
If the user is using named behaviors, then it will still need to be added manually.
> Register <serviceTelemetry> atribute automatically

- WCF/Shared/OperationContextExtensions.cs
- dirs.proj
* Allow code to compile before roslyn
* Import Global.props from dirs.proj
* Always clean before doing a full master build
> Wcf build improvements

- DependencyCallstacks/Version.props
F:\A\_work\22\obj\Release\DependencyCallstacks\Net45\AssemblyInfo.g.cs (14, 28)  
The specified version string does not conform to the required format - major[.minor[.build[.revision]]]
F:\A\_work\22\obj\Release\DependencyCallstacks\Net45\AssemblyInfo.g.cs (15, 32)  
The specified version string does not conform to the recommended format - major.minor.build.revision
F:\A\_work\22\obj\Release\DependencyCallstacks\Net40\AssemblyInfo.g.cs (14, 28)  
The specified version string does not conform to the required format - major[.minor[.build[.revision]]]
F:\A\_work\22\obj\Release\DependencyCallstacks\Net40\AssemblyInfo.g.cs (15, 32)  
The specified version string does not conform to the recommended format - major.minor.build.revision
Process 'msbuild.exe' exited with code '1'.
Related to #10
> Fixed build

- WCF/Shared.Tests/Integration/SyncStackTests.cs
- WCF/Shared.Tests/Service/ISimpleService.cs
- WCF/Shared.Tests/Service/SimpleService.cs
- WCF/Shared/ClientIpTelemetryInitializer.cs
- WCF/Shared/OperationNameTelemetryInitializer.cs
- WCF/Shared/ServiceTelemetryAttribute.cs
- WCF/Shared/UserAgentTelemetryInitializer.cs
- WCF/Shared/UserTelemetryInitializer.cs
- WCF/Version.props
- WCF/WCF.sln
- WCF/net40.tests/Microsoft.AI.Wcf.Tests.Net40.csproj
- WCF/net40.tests/app.config
- WCF/net40.tests/packages.config
- WCF/net40/Microsoft.AI.Wcf.Net40.csproj
- WCF/net40/app.config
- WCF/net40/packages.config
- WCF/net45.tests/Microsoft.AI.Wcf.Tests.Net45.csproj
- WCF/net45.tests/packages.config
- WCF/net45/Microsoft.AI.Wcf.Net45.csproj
- WCF/net45/packages.config
This PR tries to minimize access to WCF operation context in some cases to reduce the chance we'll end up trying to access a closed request message. Also updates to referencing the 2.1.0 SDK to match the core and Web SDKs.
> Minimize error chances and update to 2.1.0 SDK

- WCF/Shared.Tests/Integration/SyncStackTests.cs
- WCF/Shared.Tests/Service/ISimpleService.cs
- WCF/Shared.Tests/Service/SimpleService.cs
- WCF/Shared/RequestTrackingTelemetryModule.cs
- WCF/readme.md
This change updates documentation, and also checks that the customer code has not set `RequestTelemetry.Success` before overwriting the value. Related to issue https://github.com/Microsoft/ApplicationInsights-SDK-Labs/issues/25
> Add option to mark WCF request as failed

- WCF/Shared.Tests/Integration/SyncStackTests.cs
- WCF/Shared.Tests/Service/ISimpleService.cs
- WCF/Shared.Tests/Service/SimpleService.cs
- WCF/Shared/ClientIpTelemetryInitializer.cs
- WCF/Shared/Implementation/WcfOperationContext.cs
- WCF/Shared/OperationNameTelemetryInitializer.cs
- WCF/Shared/ServiceTelemetryAttribute.cs
- WCF/Shared/UserAgentTelemetryInitializer.cs
- WCF/Shared/UserTelemetryInitializer.cs
- WCF/Version.props
- WCF/WCF.sln
- WCF/net40.tests/Microsoft.AI.Wcf.Tests.Net40.csproj
- WCF/net40.tests/app.config
- WCF/net40.tests/packages.config
- WCF/net40/Microsoft.AI.Wcf.Net40.csproj
- WCF/net40/app.config
- WCF/net40/packages.config
- WCF/net45.tests/Microsoft.AI.Wcf.Tests.Net45.csproj
- WCF/net45.tests/packages.config
- WCF/net45/Microsoft.AI.Wcf.Net45.csproj
- WCF/net45/packages.config
Cherry-pick all commits that were affected by commit 330793d19eb0b2a4fad80c9f81a11ce50337661f that overwrote some of the WCF changes. This brings version back to 0.26 and adds WebHttpBinding support back.
Relates to Issue https://github.com/Microsoft/ApplicationInsights-SDK-Labs/issues/25
> Redo overwritten wcf commits

- AggregateMetrics/AggregateMetrics.Tests/AzureWebApp/AzureWebAppTest.cs
- AggregateMetrics/AggregateMetrics/AzureWebApp/CacheHelper.cs
- AggregateMetrics/AggregateMetrics/AzureWebApp/FlexiblePerformanceCounterGauge.cs
- Implemented CacheHelper as a singleton.
- Moved the logic that searches for a performance counter inside a json to a new method (PerformanceCounterValue).
- Added a test to check that we're correctly reading the performance counters that uses a HttpClient instead of EnvironmentVariables; using EnvironmentVariables won't work unless we're running in Azure.
> CacheHelper as singleton. Add working test.

- WCF/Shared.Tests/Integration/HostingContext.cs
- WCF/Shared.Tests/Integration/MultipleServiceCallsTests.cs
- WCF/Shared.Tests/Integration/SyncStackTests.cs
- WCF/Shared.Tests/Microsoft.AI.Wcf.Tests.projitems
- WCF/Shared.Tests/Service/AsyncService.cs
- WCF/Shared.Tests/Service/IAsyncService.cs
- WCF/Shared.Tests/Service/ISimpleService.cs
- WCF/Shared.Tests/Service/ISimpleService2.cs
- WCF/Shared.Tests/Service/SimpleService.cs
- WCF/Shared.Tests/UserAgentTelemetryInitializerTests.cs
- WCF/Shared.Tests/UserTelemetryInitializerTests.cs
- WCF/Shared/Implementation/WcfOperationContext.cs
- WCF/Shared/OperationContextExtensions.cs
Make the `WcfOperationContext` more robust with explicit checks to prevent creating a context on a WCF client-side `OperationContext` instance.
Also add a workaround for issue https://github.com/Microsoft/ApplicationInsights-SDK-Labs/issues/45.
The fundamental issue here is that the WCF design around `OperationContext` is broken: You can stack contexts through the use of `OperationContext.Current`, but there is no way to navigate from the child context back to the parent.
The workaround uses `CallContext` to track the original `OperationContext` if the service code fails to dispose the `OperationContextScope` and we end up with `OperationContext.Current` returning the wrong value.
Not sure if using `ThreadLocal<T>` coupled with an `AsyncLocal<T>` here would be better than using …
> Add checks for Wcf client operation context

- AggregateMetrics/AggregateMetrics/AzureWebApp/Implementation/CounterFactory.cs
- AggregateMetrics/AggregateMetrics/AzureWebApp/PerformanceCollectorModule.cs
+ If ReportAs value is set by the user, use it for the metrics aliases.
+ Check if the Web App is running in Azure before trying to register gauges.
> Check App is running in Azure. Use ReportAs value.

- WCF/Shared/Implementation/WcfOperationContext.cs
Check that OperationContext.Current is not null before checking for a
client-side context.
Relates to https://github.com/Microsoft/ApplicationInsights-SDK-Labs/issues/64
> Add null check on operation context

- WCF/Shared.Tests/Integration/AsyncStackTests.cs
- WCF/Shared.Tests/Service/AsyncService.cs
- WCF/Shared.Tests/Service/IAsyncService.cs
- WCF/Shared/Implementation/WcfOperationContext.cs
This is not a problem on .NET 4.6.2, where WCF correctly flows the `OperationContext` across async calls.
The fix for 4.5 - 4.6.1 would be to use `AsyncLocal<T>` to capture a reference to `WcfOperationContext`, but this is only supported in .NET 4.6, not 4.5.
So switching to use the LogicallCallContext as a work around, which should work on all of these. This should improve https://github.com/Microsoft/ApplicationInsights-SDK-Labs/issues/65
> WCF: Flow context on async calls

- WCF/Shared.Tests/MockOperationContext.cs
- WCF/Shared/IOperationContext.cs
- WCF/Shared/Implementation/RequestTrackingConstants.cs
- WCF/Shared/Implementation/WcfOperationContext.cs
- WCF/Shared/Microsoft.AI.Wcf.projitems
- WCF/Shared/RequestTrackingTelemetryModule.cs
- WCF/net40/Microsoft.AI.Wcf.Net40.csproj
- WCF/net45/Microsoft.AI.Wcf.Net45.csproj
Check if a RequestTelementry object was created by AI.Web by the time the request gets to WCF and if so, tie into it rather than generate a separate event. Relates to issue https://github.com/Microsoft/ApplicationInsights-SDK-Labs/issues/72
> Better integration with Web SDK

- WCF/NuGet/NuGet.csproj
- WCF/Shared/Implementation/PlatformContext.cs
- WCF/Shared/Implementation/WcfOperationContext.cs
- WCF/Shared/Microsoft.AI.Wcf.projitems
- WCF/net40/Microsoft.AI.Wcf.Net40.csproj
- WCF/net45/Microsoft.AI.Wcf.Net45.csproj
Addressing feedback from @SergeyKanzhelev from https://github.com/Microsoft/ApplicationInsights-SDK-Labs/pull/73.
Decided to check instead if ASP.NET Compatibility Mode is enabled in the WCF hosting layer. This will only make sense in IIS and it's required to make `HttpContext` available on the WCF threads anyway.
> Wcf http context check

- WCF/Shared.Tests/Integration/TracingTests.cs
- WCF/Shared.Tests/Microsoft.AI.Wcf.Tests.projitems
- WCF/Shared.Tests/TraceTelemetryModule.cs
- WCF/Shared/IWcfMessageTrace.cs
- WCF/Shared/Implementation/Executor.cs
- WCF/Shared/Implementation/WcfInterceptor.cs
- WCF/Shared/Microsoft.AI.Wcf.projitems
- WCF/net40.tests/ApplicationInsights.config
- WCF/net45.tests/ApplicationInsights.config
This implements the original set of changes I had made for https://github.com/Microsoft/ApplicationInsights-SDK-Labs/issues/77. Someone might still find them useful.
> Add support for IWcfMessageTrace interface in telemetry modules

- WCF/Shared/Implementation/WcfOperationContext.cs
- WCF/Version.props
Try to fix the serialization issue based on the trick on issue https://github.com/Microsoft/ApplicationInsights-SDK-Labs/issues/92 using the trick mentioned on https://github.com/Glimpse/Glimpse/issues/632#issuecomment-41484855
Also bumping version number as build was broken due to time passed since last public change.
> Fix for WcfOperationContext serialization error

- WCF/Shared/Implementation/WcfInterceptor.cs
- WCF/Shared/RequestTrackingTelemetryModule.cs
- WCF/net40/Microsoft.AI.Wcf.Net40.csproj
- WCF/net40/packages.config
- WCF/net45/Microsoft.AI.Wcf.Net45.csproj
- WCF/net45/packages.config
Add EventRegister NuGet package (closes https://github.com/Microsoft/ApplicationInsights-SDK-Labs/issues/99).
Fix `NullReferenceException` that the package revealed: the `OnEndRequest` event was being called for operations that had been excluded by the user from telemetry.
> Wcf add event register

- WCF/Shared.Tests/Microsoft.AI.Wcf.Tests.projitems
- WCF/Shared.Tests/MockOperationContext.cs
- WCF/Shared.Tests/WcfEventSourceTests.cs
- WCF/Shared/IOperationContextState.cs
- WCF/Shared/Implementation/WcfEventSource.cs
- WCF/Shared/Implementation/WcfExtensions.cs
- WCF/Shared/Implementation/WcfOperationContext.cs
- WCF/Shared/Microsoft.AI.Wcf.projitems
- WCF/Shared/OperationCorrelationTelemetryInitializer.cs
- WCF/Shared/RequestTrackingTelemetryModule.cs
- WCF/Shared/UserAgentTelemetryInitializer.cs
- WCF/Shared/UserTelemetryInitializer.cs
This PR addresses the following issues:
* Fix an error in `WcfEventSource` causing the telemetry module failures to be logged incorrectly
* Add tests for `WcfEventSource` so that this does not happen again
* Improve some ETW events to add more info
* Add code in `RequestTrackingTelemetryModule` to avoid faulting if the reply message is, somehow, closed.
* Add a mechanism to store state associated with the request in the operation context. This allows us to avoid having some telemetry initializers trigger `ObjectDisposedException` because they try to read headers/properties from the request message after it has been closed (reduce perf impact)
* Initialize the Request telemetry in OnBeginRequest rather than letting it happen when `TrackRequest()` is called, because by then the request …
> WCF - Fix EventSource + Tests + Avoid Exceptions

- WCF/Shared/OperationContextExtensions.cs
Should fix https://github.com/Microsoft/ApplicationInsights-SDK-Labs/issues/113
> Make GetRequestTelemetry() work even if OperationContext.Current is null

- WCF/Shared.Tests/ClientContractTests.cs
- WCF/Shared/Implementation/ClientContract.cs
This should fix https://github.com/Microsoft/ApplicationInsights-SDK-Labs/issues/115
> Fix handling of catch-all operations in client dependency tracking

- WCF/Shared.Tests/Integration/SyncStackTests.cs
- WCF/Shared.Tests/MockOperationContext.cs
- WCF/Shared/IOperationContext.cs
- WCF/Shared/Implementation/WcfOperationContext.cs
- WCF/Shared/RequestTrackingTelemetryModule.cs
Originally had this and then removed it, but turns out it is required in some scenarios.
One of them is adding telemetry to an application using the WCF Router Service. Since it uses generic contracts with a single, catch-all operation, there is no way to tell what the request means unless the Soap action is logged.
> Track WCF Soap Action on incoming requests

- WCF/Shared.Tests/ChannelTestBase.cs
- WCF/Shared.Tests/ClientChannelManager.cs
- WCF/Shared.Tests/ClientTelemetryExtensionElementTestscs.cs
- WCF/Shared/ClientTelemetryEndpointBehavior.cs
- WCF/Shared/ClientTelemetryExtensionElement.cs
- WCF/Shared/Implementation/ChannelAsyncResult.cs
- WCF/Shared/Implementation/ClientTelemetryBindingElement.cs
- WCF/Shared/Implementation/ClientTelemetryChannelBase.cs
- WCF/Shared/Implementation/ClientTelemetryChannelFactory.cs
- WCF/Shared/Implementation/IChannelManager.cs
- WCF/Shared/Implementation/OpenAsyncResult.cs
- WCF/Shared/Implementation/ProfilerWcfClientProcessing.cs
- WCF/Shared/Implementation/ReceiveAsyncResult.cs
- WCF/Shared/Implementation/RequestAsyncResult.cs
- WCF/Shared/Implementation/SendAsyncResult.cs
- WCF/Shared/Implementation/TryReceiveAsyncResult.cs
- WCF/Shared/WcfDependencyTrackingTelemetryModule.cs
* Add IgnoreChannelEvents property that disables logging "WCF Open Channel" dependency events
* Fix handle leak when async operations are completed synchronously in client-dependency tracking
> Add IgnoreChannelEvents + Fix handle leak

- WCF/Shared/Implementation/ClientTelemetryChannelBase.cs
Summary: _ClientTelemetryDuplexChannel_ instances are not removed from the internal _Hashtable_ used by _CommunicationObjectManager\<IChannel>_ after the channel has been closed due to the incorrect object being passed to the _OnClosed_ event handler.
Our company discovered this issue after we added the _Microsoft.ApplicationInsights.Wcf_ package to our web application so that we can record telemetry between our web application and
our internal WCF services exposed over Net.TCP. After a few hours running in Production we discovered a very high memory usage in the web application.
To reproduce this problem you need the following: 
- an ASP NET MVC web application that calls a _WCF_ service over _Net.TCP_
- the client dependency telemetry tracking feature enabled by adding the …
> Fix memory leak when using client dependency telemetry tracking feature

- WCF/NuGet/NuGet.csproj
- WCF/NuGet/Package.nuspec
- WCF/Shared.Tests/ClientTelemetryEndpointBehaviorTests.cs
- WCF/Shared/ClientTelemetryEndpointBehavior.cs
- WCF/Shared/WcfDependencyTrackingTelemetryModule.cs
- WCF/net40.tests/Microsoft.AI.Wcf.Tests.Net40.csproj
- WCF/net40.tests/packages.config
- WCF/net40/Microsoft.AI.Wcf.Net40.csproj
- WCF/net40/packages.config
- WCF/net45.tests/Microsoft.AI.Wcf.Tests.Net45.csproj
- WCF/net45.tests/packages.config
- WCF/net45/Microsoft.AI.Wcf.Net45.csproj
- WCF/net45/packages.config
This updates the WCF SDK to reference the v2.4.1 SDK assemblies.
Also fixes https://github.com/Microsoft/ApplicationInsights-SDK-Labs/issues/124.
> Updating Wcf SDK to v2.4

- WCF/Shared/ClientTelemetryEndpointBehavior.cs
- WCF/Shared/Implementation/WcfClientEventSource.cs
This update fixes the exception reported in https://github.com/Microsoft/ApplicationInsights-SDK-Labs/issues/128 when the client-dependency tracking code is enabled, and the client is doing calls to a WCF REST service (through `webHttpBinding`).
In this case, the issue is that the outgoing request message will not have an `Action` header, and so there is no easy way to tie it to the operation description on the service contract.
Some hoops could be jumped through to match the `To` header to the underlying `UriTemplate` for the operation, but this is quite complex as it requires a lot of allocations, knowing the service base address, and the HTTP method.
And even if we did this, we'd still get no better information than what the default HTTP-based dependency tracking component already …
> Do not attempt to track client calls on non-SOAP bindings

- WCF/NuGet/NuGet.csproj
Fixes error in VSTS builds:
```
##[error]Package.targets(23,5): Error : PackageVersionFile must be a valid path to a .dll file that defines NuGet package version information.
```
> Fix PackageVersionFile in WCF after removing .NET 4.0 builds
