Microsoft/ApplicationInsights-SDK-Labs

- WCF/NuGet/Package.nuspec
- WCF/NuGet/common/ApplicationInsights.config.install.xdt
- WCF/NuGet/common/ApplicationInsights.config.uninstall.xdt
- WCF/Shared.Tests/ClientIpTelemetryInitializerTests.cs
- WCF/Shared.Tests/Microsoft.AI.Wcf.Tests.projitems
- WCF/Shared/ClientIpTelemetryInitializer.cs
- WCF/Shared/Implementation/WcfEventSource.cs
- WCF/Shared/Microsoft.AI.Wcf.projitems
- WCF/net40.tests/ApplicationInsights.config
- WCF/net45.tests/ApplicationInsights.config
Also clean up some ETW stuff and remove duplication of XDT files in the NuGet package.
> Implement simple Client IP telemetry initializer

- WCF/Shared/Implementation/WcfEventSource.cs
Fixes issue https://github.com/Microsoft/ApplicationInsights-SDK-Labs/issues/13
> Fix keywords definition in WcfEventSource

- WCF/Shared.Tests/Integration/SyncStackTests.cs
- WCF/Shared.Tests/MockOperationContext.cs
- WCF/Shared.Tests/Service/ISimpleService.cs
- WCF/Shared.Tests/Service/SimpleService.cs
- WCF/Shared/IOperationContext.cs
- WCF/Shared/Implementation/WcfOperationContext.cs
- WCF/Shared/OperationNameTelemetryInitializer.cs
- WCF/Shared/RequestTrackingTelemetryModule.cs
- WCF/net40.tests/Microsoft.AI.Wcf.Tests.Net40.csproj
- WCF/net40/Microsoft.AI.Wcf.Net40.csproj
- WCF/net45.tests/Microsoft.AI.Wcf.Tests.Net45.csproj
- WCF/net45/Microsoft.AI.Wcf.Net45.csproj
Initial support for tracking requests from webHttpBinding-based services (related to https://github.com/Microsoft/ApplicationInsights-SDK-Labs/issues/15)
> Web http support

- WCF/NuGet/Package.nuspec
Fix version of references NuGet packages in nuspec file for Issue https://github.com/Microsoft/ApplicationInsights-SDK-Labs/issues/23
> Fix nuspec file to reference the right AI package versions

- AggregateMetrics/AggregateMetrics.Tests/Two/TelemetryClientExtensisonsTests.cs
- AggregateMetrics/AggregateMetrics/AggregateMetrics.csproj
- AggregateMetrics/AggregateMetrics/Two/HistogramAggregations.cs
- AggregateMetrics/AggregateMetrics/Two/Implementation/HistogramImplementation.cs
- AggregateMetrics/AggregateMetrics/Two/PercentileAggregations.cs
- AggregateMetrics/AggregateMetrics/Two/TelemetryClientExtensions.cs
Add the logic to API Two to get percentiles in a histogram.
> Add percentiles to histograms.

- AggregateMetrics/AggregateMetrics/AzureWebApp/Implementation/CounterFactory.cs
- AggregateMetrics/AggregateMetrics/AzureWebApp/PerformanceCollectorModule.cs
- AggregateMetrics/NuGet/AggregateMetrics.NuGet.csproj
- AggregateMetrics/NuGet/ApplicationInsights.config.install.xdt
- AggregateMetrics/NuGet/ApplicationInsights.config.transform
- AggregateMetrics/NuGet/ApplicationInsights.config.uninstall.xdt
- AggregateMetrics/NuGet/Package.nuspec
**+** Add modules to AI.config on NuGet install (both AggregateMetricsTelemetryModule and PerformanceCollectorModule)
**+** Change total processor time for app. processor time.
> Azure web app counters

- AggregateMetrics/AggregateMetrics/AggregateMetrics.csproj
- AggregateMetrics/AggregateMetrics/AzureWebApp/Implementation/CounterFactory.cs
- AggregateMetrics/AggregateMetrics/AzureWebApp/Implementation/PerformanceCounterFromJsonGauge.cs
- AggregateMetrics/AggregateMetrics/AzureWebApp/Implementation/RateCounterGauge.cs
- AggregateMetrics/AggregateMetrics/AzureWebApp/Implementation/SdkVersionAzureWebApp.cs
- AggregateMetrics/AggregateMetrics/AzureWebApp/Implementation/SumUpGauge.cs
- AggregateMetrics/AggregateMetrics/AzureWebApp/PerformanceCollectorModule.cs
+ Fix naming for app % Processor Time.
+ Set SDK version for Azure Web App counters telemetry.
> Set SDK version for perf. counters telemetry.

- AggregateMetrics/AggregateMetrics/AzureWebApp/ICachedEnvironmentVariableAccess.cs
- AggregateMetrics/AggregateMetrics/AzureWebApp/Implementation/AzureWebEnvironmentVariables.cs
- AggregateMetrics/AggregateMetrics/AzureWebApp/Implementation/RateCounterGauge.cs
+ Required comments in public methods and enum.
> Code compliant with StyleCop

- AggregateMetrics/AggregateMetrics.Tests/AzureWebApp/CacheHelperTests.cs
- AggregateMetrics/AggregateMetrics/AzureWebApp/Implementation/CounterFactory.cs
+ Process performance counters
> Add custom performance counters

- .gitignore
- AggregateMetrics/AggregateMetrics.Tests/AggregateMetrics.Tests.csproj
- AggregateMetrics/AggregateMetrics.Tests/AzureWebApp/CPUPercenageGaugeTests.cs
- AggregateMetrics/AggregateMetrics/AggregateMetrics.csproj
- AggregateMetrics/AggregateMetrics/AzureWebApp/Implementation/CPUPercenageGauge.cs
- AggregateMetrics/AggregateMetrics/AzureWebApp/Implementation/CounterFactory.cs
> fix CPU counters

- WCF/Shared.Tests/Integration/OneWayTests.cs
- WCF/Shared/Implementation/PlatformContext.cs
- WCF/Shared/Implementation/WcfOperationContext.cs
Addressing further feedback from @SergeyKanzhelev in https://github.com/Microsoft/ApplicationInsights-SDK-Labs/pull/74
> More WCF - Web improvements

- WCF/Shared/ExceptionTrackingTelemetryModule.cs
- WCF/Shared/RequestTrackingTelemetryModule.cs
Fixes https://github.com/Microsoft/ApplicationInsights-SDK-Labs/issues/82
> Fix warnings from 2.2.0 migration

- WCF/net40.tests/Microsoft.AI.Wcf.Tests.Net40.csproj
- WCF/net40.tests/packages.config
- WCF/net40/Microsoft.AI.Wcf.Net40.csproj
- WCF/net40/packages.config
Fix for https://github.com/Microsoft/ApplicationInsights-SDK-Labs/issues/23
> allow signing in WCF net40

- WCF/readme.md
Related to https://github.com/Microsoft/ApplicationInsights-SDK-Labs/issues/89
> Update WCF readme

- WCF/Shared/Implementation/WcfEventSource.cs
Should fix https://github.com/Microsoft/ApplicationInsights-SDK-Labs/issues/97
> Fix WcfEventSource

- WCF/Shared.Tests/WcfEventSourceTests.cs
- WCF/Shared/RequestTrackingTelemetryModule.cs
- WCF/Shared/ServiceTelemetryAttribute.cs
Fixes https://github.com/Microsoft/ApplicationInsights-SDK-Labs/issues/102
> Fix globalization errors from fxcop

- DependencyCallstacks/Net40/Net40.csproj
- DependencyCallstacks/Net40/packages.config
- DependencyCallstacks/Net40Tests/Net40.Tests.csproj
- DependencyCallstacks/Net40Tests/packages.config
- DependencyCallstacks/Net45/Net45.csproj
- DependencyCallstacks/Net45/packages.config
- DependencyCallstacks/Net45Tests/Net45.Tests.csproj
- DependencyCallstacks/Net45Tests/packages.config
Fixes https://github.com/Microsoft/ApplicationInsights-SDK-Labs/issues/107
> Updating StyleCop.MSBuild package in DependencyCallstacks to latest one

- WCF/Shared/Implementation/WcfInterceptor.cs
- WCF/Shared/Implementation/WcfOperationContext.cs
Should fix https://github.com/Microsoft/ApplicationInsights-SDK-Labs/issues/109
> Modify when we store/release the context on the call context

- WCF/NuGet/Package.nuspec
- WCF/Shared/Implementation/ProfilerWcfClientProcessing.cs
- WCF/Shared/WcfDependencyTrackingTelemetryModule.cs
- WCF/net40.tests/Microsoft.AI.Wcf.Tests.Net40.csproj
- WCF/net40.tests/packages.config
- WCF/net40/Microsoft.AI.Wcf.Net40.csproj
- WCF/net40/packages.config
- WCF/net45.tests/Microsoft.AI.Wcf.Tests.Net45.csproj
- WCF/net45.tests/packages.config
- WCF/net45/Microsoft.AI.Wcf.Net45.csproj
- WCF/net45/packages.config
PR for Issue https://github.com/Microsoft/ApplicationInsights-SDK-Labs/issues/111
> Update Wcf to v2.3 SDK

- WCF/Shared/ClientTelemetryEndpointBehavior.cs
Fix stylecop issues preventing build
> Fix broken build (stylecop)

- WCF/Shared.Tests/UserAgentTelemetryInitializerTests.cs
- WCF/Shared/UserAgentTelemetryInitializer.cs
- WCF/Version.props
Fix for https://github.com/Microsoft/ApplicationInsights-SDK-Labs/issues/139
> Fix bug reported in #139 with UserAgent tracking; update version

- dirs.proj
Possibly not ready to release and need to trigger signed builds
> Disable metrics project from builds
